[package]
name = "larq"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]
edition = "2018"

[dependencies]
arq = { path = "../../lib/arq" }
argparse="0.2"
chrono="0.4"
log="0.4"
simple_logger="1.3"
toml = "0.4"
futures = "0.1"
rusoto_core = "0.40.0"
rusoto_s3 = "0.40.0"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1"

[[bin]]
name="larq-restore"
path="src/restore/main.rs"