[package]
name = "larq"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]

[dependencies]
arq = { path = "../../lib/arq" }
argparse="0.2.1"
chrono="0.4"
log="0.3.8"
simple_logger="0.4"
toml = "0.4.5"
rusoto_core="0.30.0"
rusoto_s3="0.30.0"
serde="1.0"
serde_derive="1.0"

[[bin]]
name="larq-restore"
path="src/restore/main.rs"