[package]
name = "larq"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]
edition = "2018"

[dependencies]
argparse="0.2"
arq = { path = "../../lib/arq" }
chrono="0.4"
gumdrop = "0.8"
log="0.4"
rusoto_core = "0.40"
rusoto_s3 = "0.40"
serde = { version = "1.0", features = ["derive"] }
simple_logger="1.3"
tokio = "0.1"
toml = "0.4"
uuid = "0.8"

[[bin]]
name="larq-restore"
path="src/restore/main.rs"