[package]
name = "larq"
version = "0.1.0"
authors = ["Trent Clarke <trent.clarke@gmail.com>"]
edition = "2018"

[dependencies]
arq = { path = "../../lib/arq" }
gumdrop = "0.8"
log="0.4"
rusoto_core = "0.44"
serde = { version = "1.0", features = ["derive"] }
simple_logger="1.6"
tokio = "0.2"
toml = "0.5"
uuid = "0.8"

[[bin]]
name="larq-restore"
path="src/restore/main.rs"